language: node_js

node_js: 
   - "stable"
install:
   - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database event_manager_test_db;' -U postgres 
script:
   - npm run test

after_success:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
  - coveralls < coverage/lcov.info