language: node_js

node_js: 
   - "stable"
install:
   - npm install
services:
  - postgresql
before_script:
  - psql -c 'create database event_mamnager_test_db;' -U postgres 
script:
   - npm run test
after_success:
  - npm run coverage
